// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fdb_metadata_manager.proto

// Protobuf Java Version: 3.25.1
package cio.fdb.record.grpc;

public final class FdbMetadataManager {
  private FdbMetadataManager() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FDBDatabaseMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cio.fdb.record.grpc.FDBDatabaseMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>bytes metadataNamespace = 3;</code>
     * @return The metadataNamespace.
     */
    com.google.protobuf.ByteString getMetadataNamespace();

    /**
     * <code>bytes recordsNamespace = 4;</code>
     * @return The recordsNamespace.
     */
    com.google.protobuf.ByteString getRecordsNamespace();

    /**
     * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
     * @return Whether the metadata field is set.
     */
    boolean hasMetadata();
    /**
     * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
     * @return The metadata.
     */
    com.apple.foundationdb.record.RecordMetaDataProto.MetaData getMetadata();
    /**
     * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
     */
    com.apple.foundationdb.record.RecordMetaDataProto.MetaDataOrBuilder getMetadataOrBuilder();
  }
  /**
   * Protobuf type {@code cio.fdb.record.grpc.FDBDatabaseMetadata}
   */
  public static final class FDBDatabaseMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cio.fdb.record.grpc.FDBDatabaseMetadata)
      FDBDatabaseMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FDBDatabaseMetadata.newBuilder() to construct.
    private FDBDatabaseMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FDBDatabaseMetadata() {
      name_ = "";
      metadataNamespace_ = com.google.protobuf.ByteString.EMPTY;
      recordsNamespace_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FDBDatabaseMetadata();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.class, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_ = 0;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int METADATANAMESPACE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString metadataNamespace_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes metadataNamespace = 3;</code>
     * @return The metadataNamespace.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMetadataNamespace() {
      return metadataNamespace_;
    }

    public static final int RECORDSNAMESPACE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString recordsNamespace_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes recordsNamespace = 4;</code>
     * @return The recordsNamespace.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRecordsNamespace() {
      return recordsNamespace_;
    }

    public static final int METADATA_FIELD_NUMBER = 5;
    private com.apple.foundationdb.record.RecordMetaDataProto.MetaData metadata_;
    /**
     * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
     * @return Whether the metadata field is set.
     */
    @java.lang.Override
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
     * @return The metadata.
     */
    @java.lang.Override
    public com.apple.foundationdb.record.RecordMetaDataProto.MetaData getMetadata() {
      return metadata_ == null ? com.apple.foundationdb.record.RecordMetaDataProto.MetaData.getDefaultInstance() : metadata_;
    }
    /**
     * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
     */
    @java.lang.Override
    public com.apple.foundationdb.record.RecordMetaDataProto.MetaDataOrBuilder getMetadataOrBuilder() {
      return metadata_ == null ? com.apple.foundationdb.record.RecordMetaDataProto.MetaData.getDefaultInstance() : metadata_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasMetadata()) {
        if (!getMetadata().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (!metadataNamespace_.isEmpty()) {
        output.writeBytes(3, metadataNamespace_);
      }
      if (!recordsNamespace_.isEmpty()) {
        output.writeBytes(4, recordsNamespace_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(5, getMetadata());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (!metadataNamespace_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, metadataNamespace_);
      }
      if (!recordsNamespace_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, recordsNamespace_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMetadata());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata)) {
        return super.equals(obj);
      }
      cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata other = (cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getMetadataNamespace()
          .equals(other.getMetadataNamespace())) return false;
      if (!getRecordsNamespace()
          .equals(other.getRecordsNamespace())) return false;
      if (hasMetadata() != other.hasMetadata()) return false;
      if (hasMetadata()) {
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + METADATANAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getMetadataNamespace().hashCode();
      hash = (37 * hash) + RECORDSNAMESPACE_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsNamespace().hashCode();
      if (hasMetadata()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cio.fdb.record.grpc.FDBDatabaseMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cio.fdb.record.grpc.FDBDatabaseMetadata)
        cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.class, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.Builder.class);
      }

      // Construct using cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMetadataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        version_ = 0;
        metadataNamespace_ = com.google.protobuf.ByteString.EMPTY;
        recordsNamespace_ = com.google.protobuf.ByteString.EMPTY;
        metadata_ = null;
        if (metadataBuilder_ != null) {
          metadataBuilder_.dispose();
          metadataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_descriptor;
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata getDefaultInstanceForType() {
        return cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata build() {
        cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata buildPartial() {
        cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata result = new cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.metadataNamespace_ = metadataNamespace_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.recordsNamespace_ = recordsNamespace_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.metadata_ = metadataBuilder_ == null
              ? metadata_
              : metadataBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata) {
          return mergeFrom((cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata other) {
        if (other == cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.getMetadataNamespace() != com.google.protobuf.ByteString.EMPTY) {
          setMetadataNamespace(other.getMetadataNamespace());
        }
        if (other.getRecordsNamespace() != com.google.protobuf.ByteString.EMPTY) {
          setRecordsNamespace(other.getRecordsNamespace());
        }
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasMetadata()) {
          if (!getMetadata().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                metadataNamespace_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                recordsNamespace_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getMetadataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {

        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString metadataNamespace_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes metadataNamespace = 3;</code>
       * @return The metadataNamespace.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMetadataNamespace() {
        return metadataNamespace_;
      }
      /**
       * <code>bytes metadataNamespace = 3;</code>
       * @param value The metadataNamespace to set.
       * @return This builder for chaining.
       */
      public Builder setMetadataNamespace(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        metadataNamespace_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes metadataNamespace = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMetadataNamespace() {
        bitField0_ = (bitField0_ & ~0x00000004);
        metadataNamespace_ = getDefaultInstance().getMetadataNamespace();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString recordsNamespace_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes recordsNamespace = 4;</code>
       * @return The recordsNamespace.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getRecordsNamespace() {
        return recordsNamespace_;
      }
      /**
       * <code>bytes recordsNamespace = 4;</code>
       * @param value The recordsNamespace to set.
       * @return This builder for chaining.
       */
      public Builder setRecordsNamespace(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        recordsNamespace_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes recordsNamespace = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecordsNamespace() {
        bitField0_ = (bitField0_ & ~0x00000008);
        recordsNamespace_ = getDefaultInstance().getRecordsNamespace();
        onChanged();
        return this;
      }

      private com.apple.foundationdb.record.RecordMetaDataProto.MetaData metadata_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.apple.foundationdb.record.RecordMetaDataProto.MetaData, com.apple.foundationdb.record.RecordMetaDataProto.MetaData.Builder, com.apple.foundationdb.record.RecordMetaDataProto.MetaDataOrBuilder> metadataBuilder_;
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       * @return Whether the metadata field is set.
       */
      public boolean hasMetadata() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       * @return The metadata.
       */
      public com.apple.foundationdb.record.RecordMetaDataProto.MetaData getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_ == null ? com.apple.foundationdb.record.RecordMetaDataProto.MetaData.getDefaultInstance() : metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       */
      public Builder setMetadata(com.apple.foundationdb.record.RecordMetaDataProto.MetaData value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
        } else {
          metadataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       */
      public Builder setMetadata(
          com.apple.foundationdb.record.RecordMetaDataProto.MetaData.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       */
      public Builder mergeMetadata(com.apple.foundationdb.record.RecordMetaDataProto.MetaData value) {
        if (metadataBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            metadata_ != null &&
            metadata_ != com.apple.foundationdb.record.RecordMetaDataProto.MetaData.getDefaultInstance()) {
            getMetadataBuilder().mergeFrom(value);
          } else {
            metadata_ = value;
          }
        } else {
          metadataBuilder_.mergeFrom(value);
        }
        if (metadata_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       */
      public Builder clearMetadata() {
        bitField0_ = (bitField0_ & ~0x00000010);
        metadata_ = null;
        if (metadataBuilder_ != null) {
          metadataBuilder_.dispose();
          metadataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       */
      public com.apple.foundationdb.record.RecordMetaDataProto.MetaData.Builder getMetadataBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       */
      public com.apple.foundationdb.record.RecordMetaDataProto.MetaDataOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_ == null ?
              com.apple.foundationdb.record.RecordMetaDataProto.MetaData.getDefaultInstance() : metadata_;
        }
      }
      /**
       * <code>.com.apple.foundationdb.record.MetaData metadata = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.apple.foundationdb.record.RecordMetaDataProto.MetaData, com.apple.foundationdb.record.RecordMetaDataProto.MetaData.Builder, com.apple.foundationdb.record.RecordMetaDataProto.MetaDataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.apple.foundationdb.record.RecordMetaDataProto.MetaData, com.apple.foundationdb.record.RecordMetaDataProto.MetaData.Builder, com.apple.foundationdb.record.RecordMetaDataProto.MetaDataOrBuilder>(
                  getMetadata(),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cio.fdb.record.grpc.FDBDatabaseMetadata)
    }

    // @@protoc_insertion_point(class_scope:cio.fdb.record.grpc.FDBDatabaseMetadata)
    private static final cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata();
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FDBDatabaseMetadata>
        PARSER = new com.google.protobuf.AbstractParser<FDBDatabaseMetadata>() {
      @java.lang.Override
      public FDBDatabaseMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FDBDatabaseMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FDBDatabaseMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FDBCreateOrOpenRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cio.fdb.record.grpc.FDBCreateOrOpenRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string database = 1;</code>
     * @return The database.
     */
    java.lang.String getDatabase();
    /**
     * <code>string database = 1;</code>
     * @return The bytes for database.
     */
    com.google.protobuf.ByteString
        getDatabaseBytes();

    /**
     * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
     * @return Whether the schema field is set.
     */
    boolean hasSchema();
    /**
     * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
     * @return The schema.
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorProto getSchema();
    /**
     * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getSchemaOrBuilder();
  }
  /**
   * Protobuf type {@code cio.fdb.record.grpc.FDBCreateOrOpenRequest}
   */
  public static final class FDBCreateOrOpenRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cio.fdb.record.grpc.FDBCreateOrOpenRequest)
      FDBCreateOrOpenRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FDBCreateOrOpenRequest.newBuilder() to construct.
    private FDBCreateOrOpenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FDBCreateOrOpenRequest() {
      database_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FDBCreateOrOpenRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest.class, cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest.Builder.class);
    }

    private int bitField0_;
    public static final int DATABASE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object database_ = "";
    /**
     * <code>string database = 1;</code>
     * @return The database.
     */
    @java.lang.Override
    public java.lang.String getDatabase() {
      java.lang.Object ref = database_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        database_ = s;
        return s;
      }
    }
    /**
     * <code>string database = 1;</code>
     * @return The bytes for database.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDatabaseBytes() {
      java.lang.Object ref = database_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        database_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHEMA_FIELD_NUMBER = 2;
    private com.google.protobuf.DescriptorProtos.FileDescriptorProto schema_;
    /**
     * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
     * @return Whether the schema field is set.
     */
    @java.lang.Override
    public boolean hasSchema() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
     * @return The schema.
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorProto getSchema() {
      return schema_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance() : schema_;
    }
    /**
     * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getSchemaOrBuilder() {
      return schema_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance() : schema_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasSchema()) {
        if (!getSchema().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(database_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, database_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getSchema());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(database_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, database_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSchema());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest)) {
        return super.equals(obj);
      }
      cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest other = (cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest) obj;

      if (!getDatabase()
          .equals(other.getDatabase())) return false;
      if (hasSchema() != other.hasSchema()) return false;
      if (hasSchema()) {
        if (!getSchema()
            .equals(other.getSchema())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATABASE_FIELD_NUMBER;
      hash = (53 * hash) + getDatabase().hashCode();
      if (hasSchema()) {
        hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
        hash = (53 * hash) + getSchema().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cio.fdb.record.grpc.FDBCreateOrOpenRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cio.fdb.record.grpc.FDBCreateOrOpenRequest)
        cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest.class, cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest.Builder.class);
      }

      // Construct using cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSchemaFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        database_ = "";
        schema_ = null;
        if (schemaBuilder_ != null) {
          schemaBuilder_.dispose();
          schemaBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_descriptor;
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest getDefaultInstanceForType() {
        return cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest build() {
        cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest buildPartial() {
        cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest result = new cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.database_ = database_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.schema_ = schemaBuilder_ == null
              ? schema_
              : schemaBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest) {
          return mergeFrom((cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest other) {
        if (other == cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest.getDefaultInstance()) return this;
        if (!other.getDatabase().isEmpty()) {
          database_ = other.database_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasSchema()) {
          mergeSchema(other.getSchema());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasSchema()) {
          if (!getSchema().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                database_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getSchemaFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object database_ = "";
      /**
       * <code>string database = 1;</code>
       * @return The database.
       */
      public java.lang.String getDatabase() {
        java.lang.Object ref = database_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          database_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string database = 1;</code>
       * @return The bytes for database.
       */
      public com.google.protobuf.ByteString
          getDatabaseBytes() {
        java.lang.Object ref = database_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          database_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string database = 1;</code>
       * @param value The database to set.
       * @return This builder for chaining.
       */
      public Builder setDatabase(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        database_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string database = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatabase() {
        database_ = getDefaultInstance().getDatabase();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string database = 1;</code>
       * @param value The bytes for database to set.
       * @return This builder for chaining.
       */
      public Builder setDatabaseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        database_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.DescriptorProtos.FileDescriptorProto schema_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> schemaBuilder_;
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       * @return Whether the schema field is set.
       */
      public boolean hasSchema() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       * @return The schema.
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto getSchema() {
        if (schemaBuilder_ == null) {
          return schema_ == null ? com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance() : schema_;
        } else {
          return schemaBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       */
      public Builder setSchema(com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (schemaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          schema_ = value;
        } else {
          schemaBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       */
      public Builder setSchema(
          com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder builderForValue) {
        if (schemaBuilder_ == null) {
          schema_ = builderForValue.build();
        } else {
          schemaBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       */
      public Builder mergeSchema(com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (schemaBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            schema_ != null &&
            schema_ != com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance()) {
            getSchemaBuilder().mergeFrom(value);
          } else {
            schema_ = value;
          }
        } else {
          schemaBuilder_.mergeFrom(value);
        }
        if (schema_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       */
      public Builder clearSchema() {
        bitField0_ = (bitField0_ & ~0x00000002);
        schema_ = null;
        if (schemaBuilder_ != null) {
          schemaBuilder_.dispose();
          schemaBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder getSchemaBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSchemaFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getSchemaOrBuilder() {
        if (schemaBuilder_ != null) {
          return schemaBuilder_.getMessageOrBuilder();
        } else {
          return schema_ == null ?
              com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance() : schema_;
        }
      }
      /**
       * <code>.google.protobuf.FileDescriptorProto schema = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
          getSchemaFieldBuilder() {
        if (schemaBuilder_ == null) {
          schemaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder>(
                  getSchema(),
                  getParentForChildren(),
                  isClean());
          schema_ = null;
        }
        return schemaBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cio.fdb.record.grpc.FDBCreateOrOpenRequest)
    }

    // @@protoc_insertion_point(class_scope:cio.fdb.record.grpc.FDBCreateOrOpenRequest)
    private static final cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest();
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FDBCreateOrOpenRequest>
        PARSER = new com.google.protobuf.AbstractParser<FDBCreateOrOpenRequest>() {
      @java.lang.Override
      public FDBCreateOrOpenRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FDBCreateOrOpenRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FDBCreateOrOpenRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FDBCreateOrOpenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cio.fdb.record.grpc.FDBCreateOrOpenResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    boolean hasMetadata();
    /**
     * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
     * @return The metadata.
     */
    cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata getMetadata();
    /**
     * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
     */
    cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadataOrBuilder getMetadataOrBuilder();
  }
  /**
   * Protobuf type {@code cio.fdb.record.grpc.FDBCreateOrOpenResponse}
   */
  public static final class FDBCreateOrOpenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cio.fdb.record.grpc.FDBCreateOrOpenResponse)
      FDBCreateOrOpenResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FDBCreateOrOpenResponse.newBuilder() to construct.
    private FDBCreateOrOpenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FDBCreateOrOpenResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FDBCreateOrOpenResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse.class, cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse.Builder.class);
    }

    private int bitField0_;
    public static final int METADATA_FIELD_NUMBER = 1;
    private cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata metadata_;
    /**
     * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    @java.lang.Override
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
     * @return The metadata.
     */
    @java.lang.Override
    public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata getMetadata() {
      return metadata_ == null ? cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.getDefaultInstance() : metadata_;
    }
    /**
     * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
     */
    @java.lang.Override
    public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadataOrBuilder getMetadataOrBuilder() {
      return metadata_ == null ? cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.getDefaultInstance() : metadata_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasMetadata()) {
        if (!getMetadata().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMetadata());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMetadata());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse)) {
        return super.equals(obj);
      }
      cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse other = (cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse) obj;

      if (hasMetadata() != other.hasMetadata()) return false;
      if (hasMetadata()) {
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMetadata()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cio.fdb.record.grpc.FDBCreateOrOpenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cio.fdb.record.grpc.FDBCreateOrOpenResponse)
        cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse.class, cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse.Builder.class);
      }

      // Construct using cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMetadataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        metadata_ = null;
        if (metadataBuilder_ != null) {
          metadataBuilder_.dispose();
          metadataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cio.fdb.record.grpc.FdbMetadataManager.internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_descriptor;
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse getDefaultInstanceForType() {
        return cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse build() {
        cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse buildPartial() {
        cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse result = new cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.metadata_ = metadataBuilder_ == null
              ? metadata_
              : metadataBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse) {
          return mergeFrom((cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse other) {
        if (other == cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse.getDefaultInstance()) return this;
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasMetadata()) {
          if (!getMetadata().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMetadataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata metadata_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.Builder, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadataOrBuilder> metadataBuilder_;
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       * @return Whether the metadata field is set.
       */
      public boolean hasMetadata() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       * @return The metadata.
       */
      public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_ == null ? cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.getDefaultInstance() : metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       */
      public Builder setMetadata(cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
        } else {
          metadataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       */
      public Builder setMetadata(
          cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       */
      public Builder mergeMetadata(cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata value) {
        if (metadataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            metadata_ != null &&
            metadata_ != cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.getDefaultInstance()) {
            getMetadataBuilder().mergeFrom(value);
          } else {
            metadata_ = value;
          }
        } else {
          metadataBuilder_.mergeFrom(value);
        }
        if (metadata_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       */
      public Builder clearMetadata() {
        bitField0_ = (bitField0_ & ~0x00000001);
        metadata_ = null;
        if (metadataBuilder_ != null) {
          metadataBuilder_.dispose();
          metadataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       */
      public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.Builder getMetadataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       */
      public cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadataOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_ == null ?
              cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.getDefaultInstance() : metadata_;
        }
      }
      /**
       * <code>.cio.fdb.record.grpc.FDBDatabaseMetadata metadata = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.Builder, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadata.Builder, cio.fdb.record.grpc.FdbMetadataManager.FDBDatabaseMetadataOrBuilder>(
                  getMetadata(),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cio.fdb.record.grpc.FDBCreateOrOpenResponse)
    }

    // @@protoc_insertion_point(class_scope:cio.fdb.record.grpc.FDBCreateOrOpenResponse)
    private static final cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse();
    }

    public static cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FDBCreateOrOpenResponse>
        PARSER = new com.google.protobuf.AbstractParser<FDBCreateOrOpenResponse>() {
      @java.lang.Override
      public FDBCreateOrOpenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FDBCreateOrOpenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FDBCreateOrOpenResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cio.fdb.record.grpc.FdbMetadataManager.FDBCreateOrOpenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032fdb_metadata_manager.proto\022\023cio.fdb.re" +
      "cord.grpc\032 google/protobuf/descriptor.pr" +
      "oto\032\025record_metadata.proto\"\244\001\n\023FDBDataba" +
      "seMetadata\022\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002 \001(" +
      "\005\022\031\n\021metadataNamespace\030\003 \001(\014\022\030\n\020recordsN" +
      "amespace\030\004 \001(\014\0229\n\010metadata\030\005 \001(\0132\'.com.a" +
      "pple.foundationdb.record.MetaData\"`\n\026FDB" +
      "CreateOrOpenRequest\022\020\n\010database\030\001 \001(\t\0224\n" +
      "\006schema\030\002 \001(\0132$.google.protobuf.FileDesc" +
      "riptorProto\"U\n\027FDBCreateOrOpenResponse\022:" +
      "\n\010metadata\030\001 \001(\0132(.cio.fdb.record.grpc.F" +
      "DBDatabaseMetadata2\201\001\n\022FDBMetadataManage" +
      "r\022k\n\014CreateOrOpen\022+.cio.fdb.record.grpc." +
      "FDBCreateOrOpenRequest\032,.cio.fdb.record." +
      "grpc.FDBCreateOrOpenResponse\"\000B*\n\023cio.fd" +
      "b.record.grpcZ\023cio/fdb/grpc/protosb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.apple.foundationdb.record.RecordMetaDataProto.getDescriptor(),
        });
    internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cio_fdb_record_grpc_FDBDatabaseMetadata_descriptor,
        new java.lang.String[] { "Name", "Version", "MetadataNamespace", "RecordsNamespace", "Metadata", });
    internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cio_fdb_record_grpc_FDBCreateOrOpenRequest_descriptor,
        new java.lang.String[] { "Database", "Schema", });
    internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cio_fdb_record_grpc_FDBCreateOrOpenResponse_descriptor,
        new java.lang.String[] { "Metadata", });
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.apple.foundationdb.record.RecordMetaDataProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
