//
// record_metadata_options.proto
//
// This source file is part of the FoundationDB open source project
//
// Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: record_metadata_options.proto

package src

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordTypeOptions_Usage int32

const (
	RecordTypeOptions_UNSET  RecordTypeOptions_Usage = 0
	RecordTypeOptions_RECORD RecordTypeOptions_Usage = 1
	RecordTypeOptions_UNION  RecordTypeOptions_Usage = 2
	RecordTypeOptions_NESTED RecordTypeOptions_Usage = 3
)

// Enum value maps for RecordTypeOptions_Usage.
var (
	RecordTypeOptions_Usage_name = map[int32]string{
		0: "UNSET",
		1: "RECORD",
		2: "UNION",
		3: "NESTED",
	}
	RecordTypeOptions_Usage_value = map[string]int32{
		"UNSET":  0,
		"RECORD": 1,
		"UNION":  2,
		"NESTED": 3,
	}
)

func (x RecordTypeOptions_Usage) Enum() *RecordTypeOptions_Usage {
	p := new(RecordTypeOptions_Usage)
	*p = x
	return p
}

func (x RecordTypeOptions_Usage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecordTypeOptions_Usage) Descriptor() protoreflect.EnumDescriptor {
	return file_record_metadata_options_proto_enumTypes[0].Descriptor()
}

func (RecordTypeOptions_Usage) Type() protoreflect.EnumType {
	return &file_record_metadata_options_proto_enumTypes[0]
}

func (x RecordTypeOptions_Usage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RecordTypeOptions_Usage) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RecordTypeOptions_Usage(num)
	return nil
}

// Deprecated: Use RecordTypeOptions_Usage.Descriptor instead.
func (RecordTypeOptions_Usage) EnumDescriptor() ([]byte, []int) {
	return file_record_metadata_options_proto_rawDescGZIP(), []int{1, 0}
}

type SchemaOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SplitLongRecords    *bool `protobuf:"varint,3,opt,name=split_long_records,json=splitLongRecords" json:"split_long_records,omitempty"`
	StoreRecordVersions *bool `protobuf:"varint,4,opt,name=store_record_versions,json=storeRecordVersions" json:"store_record_versions,omitempty"`
}

func (x *SchemaOptions) Reset() {
	*x = SchemaOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_metadata_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaOptions) ProtoMessage() {}

func (x *SchemaOptions) ProtoReflect() protoreflect.Message {
	mi := &file_record_metadata_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaOptions.ProtoReflect.Descriptor instead.
func (*SchemaOptions) Descriptor() ([]byte, []int) {
	return file_record_metadata_options_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaOptions) GetSplitLongRecords() bool {
	if x != nil && x.SplitLongRecords != nil {
		return *x.SplitLongRecords
	}
	return false
}

func (x *SchemaOptions) GetStoreRecordVersions() bool {
	if x != nil && x.StoreRecordVersions != nil {
		return *x.StoreRecordVersions
	}
	return false
}

type RecordTypeOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usage         *RecordTypeOptions_Usage `protobuf:"varint,1,opt,name=usage,enum=com.apple.foundationdb.record.RecordTypeOptions_Usage,def=0" json:"usage,omitempty"`
	SinceVersion  *int32                   `protobuf:"varint,2,opt,name=since_version,json=sinceVersion" json:"since_version,omitempty"` // This record_type is introduced on this metadata version
	RecordTypeKey *Value                   `protobuf:"bytes,3,opt,name=record_type_key,json=recordTypeKey" json:"record_type_key,omitempty"`
}

// Default values for RecordTypeOptions fields.
const (
	Default_RecordTypeOptions_Usage = RecordTypeOptions_UNSET
)

func (x *RecordTypeOptions) Reset() {
	*x = RecordTypeOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_metadata_options_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordTypeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTypeOptions) ProtoMessage() {}

func (x *RecordTypeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_record_metadata_options_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTypeOptions.ProtoReflect.Descriptor instead.
func (*RecordTypeOptions) Descriptor() ([]byte, []int) {
	return file_record_metadata_options_proto_rawDescGZIP(), []int{1}
}

func (x *RecordTypeOptions) GetUsage() RecordTypeOptions_Usage {
	if x != nil && x.Usage != nil {
		return *x.Usage
	}
	return Default_RecordTypeOptions_Usage
}

func (x *RecordTypeOptions) GetSinceVersion() int32 {
	if x != nil && x.SinceVersion != nil {
		return *x.SinceVersion
	}
	return 0
}

func (x *RecordTypeOptions) GetRecordTypeKey() *Value {
	if x != nil {
		return x.RecordTypeKey
	}
	return nil
}

type FieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Marked as deprecated in record_metadata_options.proto.
	Indexed    *Index_Type               `protobuf:"varint,1,opt,name=indexed,enum=com.apple.foundationdb.record.Index_Type" json:"indexed,omitempty"` // Use index.type.
	PrimaryKey *bool                     `protobuf:"varint,2,opt,name=primary_key,json=primaryKey" json:"primary_key,omitempty"`
	Index      *FieldOptions_IndexOption `protobuf:"bytes,3,opt,name=index" json:"index,omitempty"`
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_metadata_options_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_record_metadata_options_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_record_metadata_options_proto_rawDescGZIP(), []int{2}
}

// Deprecated: Marked as deprecated in record_metadata_options.proto.
func (x *FieldOptions) GetIndexed() Index_Type {
	if x != nil && x.Indexed != nil {
		return *x.Indexed
	}
	return Index_INDEX
}

func (x *FieldOptions) GetPrimaryKey() bool {
	if x != nil && x.PrimaryKey != nil {
		return *x.PrimaryKey
	}
	return false
}

func (x *FieldOptions) GetIndex() *FieldOptions_IndexOption {
	if x != nil {
		return x.Index
	}
	return nil
}

type FieldOptions_IndexOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    *string         `protobuf:"bytes,1,opt,name=type,def=value" json:"type,omitempty"`
	Unique  *bool           `protobuf:"varint,2,opt,name=unique" json:"unique,omitempty"`
	Options []*Index_Option `protobuf:"bytes,3,rep,name=options" json:"options,omitempty"` // Note: there is no way to specify these in a .proto file.
}

// Default values for FieldOptions_IndexOption fields.
const (
	Default_FieldOptions_IndexOption_Type = string("value")
)

func (x *FieldOptions_IndexOption) Reset() {
	*x = FieldOptions_IndexOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_metadata_options_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldOptions_IndexOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions_IndexOption) ProtoMessage() {}

func (x *FieldOptions_IndexOption) ProtoReflect() protoreflect.Message {
	mi := &file_record_metadata_options_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions_IndexOption.ProtoReflect.Descriptor instead.
func (*FieldOptions_IndexOption) Descriptor() ([]byte, []int) {
	return file_record_metadata_options_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FieldOptions_IndexOption) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_FieldOptions_IndexOption_Type
}

func (x *FieldOptions_IndexOption) GetUnique() bool {
	if x != nil && x.Unique != nil {
		return *x.Unique
	}
	return false
}

func (x *FieldOptions_IndexOption) GetOptions() []*Index_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

var file_record_metadata_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*SchemaOptions)(nil),
		Field:         1233,
		Name:          "com.apple.foundationdb.record.schema",
		Tag:           "bytes,1233,opt,name=schema",
		Filename:      "record_metadata_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*RecordTypeOptions)(nil),
		Field:         1233,
		Name:          "com.apple.foundationdb.record.record",
		Tag:           "bytes,1233,opt,name=record",
		Filename:      "record_metadata_options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         1233,
		Name:          "com.apple.foundationdb.record.field",
		Tag:           "bytes,1233,opt,name=field",
		Filename:      "record_metadata_options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional com.apple.foundationdb.record.SchemaOptions schema = 1233;
	E_Schema = &file_record_metadata_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional com.apple.foundationdb.record.RecordTypeOptions record = 1233;
	E_Record = &file_record_metadata_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional com.apple.foundationdb.record.FieldOptions field = 1233;
	E_Field = &file_record_metadata_options_proto_extTypes[2]
)

var File_record_metadata_options_proto protoreflect.FileDescriptor

var file_record_metadata_options_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x71, 0x0a, 0x0d, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x70, 0x6c, 0x69,
	0x74, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x92, 0x02, 0x0a, 0x11, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x53, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x36, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x55, 0x73, 0x61, 0x67, 0x65, 0x3a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x52, 0x05,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x69, 0x6e, 0x63, 0x65, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x73, 0x69,
	0x6e, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4c, 0x0a, 0x0f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x05, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x45, 0x43, 0x4f, 0x52, 0x44, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x49, 0x4f,
	0x4e, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x45, 0x53, 0x54, 0x45, 0x44, 0x10, 0x03, 0x22,
	0xd1, 0x02, 0x0a, 0x0c, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x47, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x42, 0x02, 0x18, 0x01,
	0x52, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69,
	0x6d, 0x61, 0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x4d, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x1a, 0x87, 0x01, 0x0a, 0x0b, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x12, 0x45, 0x0a, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x3a, 0x63, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1c, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x3a, 0x6a, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x3a, 0x61, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd1, 0x09, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x30, 0x42, 0x1a, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x12, 0x63, 0x69, 0x6f, 0x2f, 0x66, 0x64, 0x62, 0x2f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x73, 0x72, 0x63,
}

var (
	file_record_metadata_options_proto_rawDescOnce sync.Once
	file_record_metadata_options_proto_rawDescData = file_record_metadata_options_proto_rawDesc
)

func file_record_metadata_options_proto_rawDescGZIP() []byte {
	file_record_metadata_options_proto_rawDescOnce.Do(func() {
		file_record_metadata_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_record_metadata_options_proto_rawDescData)
	})
	return file_record_metadata_options_proto_rawDescData
}

var file_record_metadata_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_record_metadata_options_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_record_metadata_options_proto_goTypes = []any{
	(RecordTypeOptions_Usage)(0),        // 0: com.apple.foundationdb.record.RecordTypeOptions.Usage
	(*SchemaOptions)(nil),               // 1: com.apple.foundationdb.record.SchemaOptions
	(*RecordTypeOptions)(nil),           // 2: com.apple.foundationdb.record.RecordTypeOptions
	(*FieldOptions)(nil),                // 3: com.apple.foundationdb.record.FieldOptions
	(*FieldOptions_IndexOption)(nil),    // 4: com.apple.foundationdb.record.FieldOptions.IndexOption
	(*Value)(nil),                       // 5: com.apple.foundationdb.record.Value
	(Index_Type)(0),                     // 6: com.apple.foundationdb.record.Index.Type
	(*Index_Option)(nil),                // 7: com.apple.foundationdb.record.Index.Option
	(*descriptorpb.FileOptions)(nil),    // 8: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 10: google.protobuf.FieldOptions
}
var file_record_metadata_options_proto_depIdxs = []int32{
	0,  // 0: com.apple.foundationdb.record.RecordTypeOptions.usage:type_name -> com.apple.foundationdb.record.RecordTypeOptions.Usage
	5,  // 1: com.apple.foundationdb.record.RecordTypeOptions.record_type_key:type_name -> com.apple.foundationdb.record.Value
	6,  // 2: com.apple.foundationdb.record.FieldOptions.indexed:type_name -> com.apple.foundationdb.record.Index.Type
	4,  // 3: com.apple.foundationdb.record.FieldOptions.index:type_name -> com.apple.foundationdb.record.FieldOptions.IndexOption
	7,  // 4: com.apple.foundationdb.record.FieldOptions.IndexOption.options:type_name -> com.apple.foundationdb.record.Index.Option
	8,  // 5: com.apple.foundationdb.record.schema:extendee -> google.protobuf.FileOptions
	9,  // 6: com.apple.foundationdb.record.record:extendee -> google.protobuf.MessageOptions
	10, // 7: com.apple.foundationdb.record.field:extendee -> google.protobuf.FieldOptions
	1,  // 8: com.apple.foundationdb.record.schema:type_name -> com.apple.foundationdb.record.SchemaOptions
	2,  // 9: com.apple.foundationdb.record.record:type_name -> com.apple.foundationdb.record.RecordTypeOptions
	3,  // 10: com.apple.foundationdb.record.field:type_name -> com.apple.foundationdb.record.FieldOptions
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	8,  // [8:11] is the sub-list for extension type_name
	5,  // [5:8] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_record_metadata_options_proto_init() }
func file_record_metadata_options_proto_init() {
	if File_record_metadata_options_proto != nil {
		return
	}
	file_record_metadata_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_record_metadata_options_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SchemaOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_metadata_options_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RecordTypeOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_metadata_options_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_metadata_options_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FieldOptions_IndexOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_record_metadata_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_record_metadata_options_proto_goTypes,
		DependencyIndexes: file_record_metadata_options_proto_depIdxs,
		EnumInfos:         file_record_metadata_options_proto_enumTypes,
		MessageInfos:      file_record_metadata_options_proto_msgTypes,
		ExtensionInfos:    file_record_metadata_options_proto_extTypes,
	}.Build()
	File_record_metadata_options_proto = out.File
	file_record_metadata_options_proto_rawDesc = nil
	file_record_metadata_options_proto_goTypes = nil
	file_record_metadata_options_proto_depIdxs = nil
}
