//
// record_cursor.proto
//
// This source file is part of the FoundationDB open source project
//
// Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: record_cursor.proto

package src

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrElseContinuation_State int32

const (
	OrElseContinuation_UNDECIDED OrElseContinuation_State = 0
	OrElseContinuation_USE_INNER OrElseContinuation_State = 1
	OrElseContinuation_USE_OTHER OrElseContinuation_State = 2
)

// Enum value maps for OrElseContinuation_State.
var (
	OrElseContinuation_State_name = map[int32]string{
		0: "UNDECIDED",
		1: "USE_INNER",
		2: "USE_OTHER",
	}
	OrElseContinuation_State_value = map[string]int32{
		"UNDECIDED": 0,
		"USE_INNER": 1,
		"USE_OTHER": 2,
	}
)

func (x OrElseContinuation_State) Enum() *OrElseContinuation_State {
	p := new(OrElseContinuation_State)
	*p = x
	return p
}

func (x OrElseContinuation_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrElseContinuation_State) Descriptor() protoreflect.EnumDescriptor {
	return file_record_cursor_proto_enumTypes[0].Descriptor()
}

func (OrElseContinuation_State) Type() protoreflect.EnumType {
	return &file_record_cursor_proto_enumTypes[0]
}

func (x OrElseContinuation_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OrElseContinuation_State) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OrElseContinuation_State(num)
	return nil
}

// Deprecated: Use OrElseContinuation_State.Descriptor instead.
func (OrElseContinuation_State) EnumDescriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{7, 0}
}

type FlatMapContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OuterContinuation []byte `protobuf:"bytes,1,opt,name=outer_continuation,json=outerContinuation" json:"outer_continuation,omitempty"`
	InnerContinuation []byte `protobuf:"bytes,2,opt,name=inner_continuation,json=innerContinuation" json:"inner_continuation,omitempty"`
	CheckValue        []byte `protobuf:"bytes,3,opt,name=check_value,json=checkValue" json:"check_value,omitempty"`
}

func (x *FlatMapContinuation) Reset() {
	*x = FlatMapContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FlatMapContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatMapContinuation) ProtoMessage() {}

func (x *FlatMapContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatMapContinuation.ProtoReflect.Descriptor instead.
func (*FlatMapContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{0}
}

func (x *FlatMapContinuation) GetOuterContinuation() []byte {
	if x != nil {
		return x.OuterContinuation
	}
	return nil
}

func (x *FlatMapContinuation) GetInnerContinuation() []byte {
	if x != nil {
		return x.InnerContinuation
	}
	return nil
}

func (x *FlatMapContinuation) GetCheckValue() []byte {
	if x != nil {
		return x.CheckValue
	}
	return nil
}

type IntersectionContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstContinuation  []byte                                  `protobuf:"bytes,1,opt,name=first_continuation,json=firstContinuation" json:"first_continuation,omitempty"`
	SecondContinuation []byte                                  `protobuf:"bytes,2,opt,name=second_continuation,json=secondContinuation" json:"second_continuation,omitempty"`
	FirstStarted       *bool                                   `protobuf:"varint,3,opt,name=first_started,json=firstStarted" json:"first_started,omitempty"`
	SecondStarted      *bool                                   `protobuf:"varint,4,opt,name=second_started,json=secondStarted" json:"second_started,omitempty"`
	OtherChildState    []*IntersectionContinuation_CursorState `protobuf:"bytes,5,rep,name=other_child_state,json=otherChildState" json:"other_child_state,omitempty"`
}

func (x *IntersectionContinuation) Reset() {
	*x = IntersectionContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntersectionContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntersectionContinuation) ProtoMessage() {}

func (x *IntersectionContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntersectionContinuation.ProtoReflect.Descriptor instead.
func (*IntersectionContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{1}
}

func (x *IntersectionContinuation) GetFirstContinuation() []byte {
	if x != nil {
		return x.FirstContinuation
	}
	return nil
}

func (x *IntersectionContinuation) GetSecondContinuation() []byte {
	if x != nil {
		return x.SecondContinuation
	}
	return nil
}

func (x *IntersectionContinuation) GetFirstStarted() bool {
	if x != nil && x.FirstStarted != nil {
		return *x.FirstStarted
	}
	return false
}

func (x *IntersectionContinuation) GetSecondStarted() bool {
	if x != nil && x.SecondStarted != nil {
		return *x.SecondStarted
	}
	return false
}

func (x *IntersectionContinuation) GetOtherChildState() []*IntersectionContinuation_CursorState {
	if x != nil {
		return x.OtherChildState
	}
	return nil
}

type UnionContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstContinuation  []byte                           `protobuf:"bytes,1,opt,name=first_continuation,json=firstContinuation" json:"first_continuation,omitempty"`
	SecondContinuation []byte                           `protobuf:"bytes,2,opt,name=second_continuation,json=secondContinuation" json:"second_continuation,omitempty"`
	FirstExhausted     *bool                            `protobuf:"varint,3,opt,name=first_exhausted,json=firstExhausted" json:"first_exhausted,omitempty"`
	SecondExhausted    *bool                            `protobuf:"varint,4,opt,name=second_exhausted,json=secondExhausted" json:"second_exhausted,omitempty"`
	OtherChildState    []*UnionContinuation_CursorState `protobuf:"bytes,5,rep,name=other_child_state,json=otherChildState" json:"other_child_state,omitempty"`
}

func (x *UnionContinuation) Reset() {
	*x = UnionContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnionContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionContinuation) ProtoMessage() {}

func (x *UnionContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionContinuation.ProtoReflect.Descriptor instead.
func (*UnionContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{2}
}

func (x *UnionContinuation) GetFirstContinuation() []byte {
	if x != nil {
		return x.FirstContinuation
	}
	return nil
}

func (x *UnionContinuation) GetSecondContinuation() []byte {
	if x != nil {
		return x.SecondContinuation
	}
	return nil
}

func (x *UnionContinuation) GetFirstExhausted() bool {
	if x != nil && x.FirstExhausted != nil {
		return *x.FirstExhausted
	}
	return false
}

func (x *UnionContinuation) GetSecondExhausted() bool {
	if x != nil && x.SecondExhausted != nil {
		return *x.SecondExhausted
	}
	return false
}

func (x *UnionContinuation) GetOtherChildState() []*UnionContinuation_CursorState {
	if x != nil {
		return x.OtherChildState
	}
	return nil
}

type ProbableIntersectionContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChildState []*ProbableIntersectionContinuation_CursorState `protobuf:"bytes,1,rep,name=child_state,json=childState" json:"child_state,omitempty"`
}

func (x *ProbableIntersectionContinuation) Reset() {
	*x = ProbableIntersectionContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbableIntersectionContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbableIntersectionContinuation) ProtoMessage() {}

func (x *ProbableIntersectionContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbableIntersectionContinuation.ProtoReflect.Descriptor instead.
func (*ProbableIntersectionContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{3}
}

func (x *ProbableIntersectionContinuation) GetChildState() []*ProbableIntersectionContinuation_CursorState {
	if x != nil {
		return x.ChildState
	}
	return nil
}

type ConcatContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Second       *bool  `protobuf:"varint,1,opt,name=second" json:"second,omitempty"` //true if the continuation applies to second cursor
	Continuation []byte `protobuf:"bytes,3,opt,name=continuation" json:"continuation,omitempty"`
}

func (x *ConcatContinuation) Reset() {
	*x = ConcatContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConcatContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcatContinuation) ProtoMessage() {}

func (x *ConcatContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcatContinuation.ProtoReflect.Descriptor instead.
func (*ConcatContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{4}
}

func (x *ConcatContinuation) GetSecond() bool {
	if x != nil && x.Second != nil {
		return *x.Second
	}
	return false
}

func (x *ConcatContinuation) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

type SizeStatisticsContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continuation   []byte                        `protobuf:"bytes,1,opt,name=continuation" json:"continuation,omitempty"`
	PartialResults *SizeStatisticsPartialResults `protobuf:"bytes,2,opt,name=partialResults" json:"partialResults,omitempty"`
}

func (x *SizeStatisticsContinuation) Reset() {
	*x = SizeStatisticsContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeStatisticsContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeStatisticsContinuation) ProtoMessage() {}

func (x *SizeStatisticsContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeStatisticsContinuation.ProtoReflect.Descriptor instead.
func (*SizeStatisticsContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{5}
}

func (x *SizeStatisticsContinuation) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *SizeStatisticsContinuation) GetPartialResults() *SizeStatisticsPartialResults {
	if x != nil {
		return x.PartialResults
	}
	return nil
}

type SizeStatisticsPartialResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyCount     *uint64  `protobuf:"varint,1,opt,name=keyCount" json:"keyCount,omitempty"`
	KeySize      *uint64  `protobuf:"varint,2,opt,name=keySize" json:"keySize,omitempty"`
	MaxKeySize   *uint64  `protobuf:"varint,3,opt,name=maxKeySize" json:"maxKeySize,omitempty"`
	ValueSize    *uint64  `protobuf:"varint,4,opt,name=valueSize" json:"valueSize,omitempty"`
	MaxValueSize *uint64  `protobuf:"varint,5,opt,name=maxValueSize" json:"maxValueSize,omitempty"`
	SizeBuckets  []uint64 `protobuf:"varint,6,rep,packed,name=sizeBuckets" json:"sizeBuckets,omitempty"`
}

func (x *SizeStatisticsPartialResults) Reset() {
	*x = SizeStatisticsPartialResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeStatisticsPartialResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeStatisticsPartialResults) ProtoMessage() {}

func (x *SizeStatisticsPartialResults) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeStatisticsPartialResults.ProtoReflect.Descriptor instead.
func (*SizeStatisticsPartialResults) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{6}
}

func (x *SizeStatisticsPartialResults) GetKeyCount() uint64 {
	if x != nil && x.KeyCount != nil {
		return *x.KeyCount
	}
	return 0
}

func (x *SizeStatisticsPartialResults) GetKeySize() uint64 {
	if x != nil && x.KeySize != nil {
		return *x.KeySize
	}
	return 0
}

func (x *SizeStatisticsPartialResults) GetMaxKeySize() uint64 {
	if x != nil && x.MaxKeySize != nil {
		return *x.MaxKeySize
	}
	return 0
}

func (x *SizeStatisticsPartialResults) GetValueSize() uint64 {
	if x != nil && x.ValueSize != nil {
		return *x.ValueSize
	}
	return 0
}

func (x *SizeStatisticsPartialResults) GetMaxValueSize() uint64 {
	if x != nil && x.MaxValueSize != nil {
		return *x.MaxValueSize
	}
	return 0
}

func (x *SizeStatisticsPartialResults) GetSizeBuckets() []uint64 {
	if x != nil {
		return x.SizeBuckets
	}
	return nil
}

type OrElseContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State        *OrElseContinuation_State `protobuf:"varint,1,opt,name=state,enum=com.apple.foundationdb.record.OrElseContinuation_State" json:"state,omitempty"`
	Continuation []byte                    `protobuf:"bytes,2,opt,name=continuation" json:"continuation,omitempty"`
}

func (x *OrElseContinuation) Reset() {
	*x = OrElseContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrElseContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrElseContinuation) ProtoMessage() {}

func (x *OrElseContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrElseContinuation.ProtoReflect.Descriptor instead.
func (*OrElseContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{7}
}

func (x *OrElseContinuation) GetState() OrElseContinuation_State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return OrElseContinuation_UNDECIDED
}

func (x *OrElseContinuation) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

type ComposedBitmapIndexContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChildState []*ComposedBitmapIndexContinuation_CursorState `protobuf:"bytes,1,rep,name=child_state,json=childState" json:"child_state,omitempty"`
}

func (x *ComposedBitmapIndexContinuation) Reset() {
	*x = ComposedBitmapIndexContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposedBitmapIndexContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposedBitmapIndexContinuation) ProtoMessage() {}

func (x *ComposedBitmapIndexContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposedBitmapIndexContinuation.ProtoReflect.Descriptor instead.
func (*ComposedBitmapIndexContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{8}
}

func (x *ComposedBitmapIndexContinuation) GetChildState() []*ComposedBitmapIndexContinuation_CursorState {
	if x != nil {
		return x.ChildState
	}
	return nil
}

type SelectorPlanContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelectedPlan      *uint64 `protobuf:"varint,1,opt,name=selected_plan,json=selectedPlan" json:"selected_plan,omitempty"`               // The selected plan executing from the list of optional plans
	InnerContinuation []byte  `protobuf:"bytes,2,opt,name=inner_continuation,json=innerContinuation" json:"inner_continuation,omitempty"` // The selected plan's continuation
}

func (x *SelectorPlanContinuation) Reset() {
	*x = SelectorPlanContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectorPlanContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectorPlanContinuation) ProtoMessage() {}

func (x *SelectorPlanContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectorPlanContinuation.ProtoReflect.Descriptor instead.
func (*SelectorPlanContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{9}
}

func (x *SelectorPlanContinuation) GetSelectedPlan() uint64 {
	if x != nil && x.SelectedPlan != nil {
		return *x.SelectedPlan
	}
	return 0
}

func (x *SelectorPlanContinuation) GetInnerContinuation() []byte {
	if x != nil {
		return x.InnerContinuation
	}
	return nil
}

type ComparatorContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChildState []*ComparatorContinuation_CursorState `protobuf:"bytes,1,rep,name=child_state,json=childState" json:"child_state,omitempty"`
}

func (x *ComparatorContinuation) Reset() {
	*x = ComparatorContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComparatorContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparatorContinuation) ProtoMessage() {}

func (x *ComparatorContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparatorContinuation.ProtoReflect.Descriptor instead.
func (*ComparatorContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{10}
}

func (x *ComparatorContinuation) GetChildState() []*ComparatorContinuation_CursorState {
	if x != nil {
		return x.ChildState
	}
	return nil
}

type MultidimensionalIndexScanContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastHilbertValue []byte `protobuf:"bytes,1,opt,name=lastHilbertValue" json:"lastHilbertValue,omitempty"`
	LastKey          []byte `protobuf:"bytes,2,opt,name=lastKey" json:"lastKey,omitempty"`
}

func (x *MultidimensionalIndexScanContinuation) Reset() {
	*x = MultidimensionalIndexScanContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultidimensionalIndexScanContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultidimensionalIndexScanContinuation) ProtoMessage() {}

func (x *MultidimensionalIndexScanContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultidimensionalIndexScanContinuation.ProtoReflect.Descriptor instead.
func (*MultidimensionalIndexScanContinuation) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{11}
}

func (x *MultidimensionalIndexScanContinuation) GetLastHilbertValue() []byte {
	if x != nil {
		return x.LastHilbertValue
	}
	return nil
}

func (x *MultidimensionalIndexScanContinuation) GetLastKey() []byte {
	if x != nil {
		return x.LastKey
	}
	return nil
}

type IntersectionContinuation_CursorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continuation []byte `protobuf:"bytes,1,opt,name=continuation" json:"continuation,omitempty"`
	Started      *bool  `protobuf:"varint,2,opt,name=started" json:"started,omitempty"`
}

func (x *IntersectionContinuation_CursorState) Reset() {
	*x = IntersectionContinuation_CursorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntersectionContinuation_CursorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntersectionContinuation_CursorState) ProtoMessage() {}

func (x *IntersectionContinuation_CursorState) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntersectionContinuation_CursorState.ProtoReflect.Descriptor instead.
func (*IntersectionContinuation_CursorState) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{1, 0}
}

func (x *IntersectionContinuation_CursorState) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *IntersectionContinuation_CursorState) GetStarted() bool {
	if x != nil && x.Started != nil {
		return *x.Started
	}
	return false
}

type UnionContinuation_CursorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continuation []byte `protobuf:"bytes,1,opt,name=continuation" json:"continuation,omitempty"`
	Exhausted    *bool  `protobuf:"varint,2,opt,name=exhausted" json:"exhausted,omitempty"`
}

func (x *UnionContinuation_CursorState) Reset() {
	*x = UnionContinuation_CursorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnionContinuation_CursorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionContinuation_CursorState) ProtoMessage() {}

func (x *UnionContinuation_CursorState) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionContinuation_CursorState.ProtoReflect.Descriptor instead.
func (*UnionContinuation_CursorState) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UnionContinuation_CursorState) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *UnionContinuation_CursorState) GetExhausted() bool {
	if x != nil && x.Exhausted != nil {
		return *x.Exhausted
	}
	return false
}

type ProbableIntersectionContinuation_CursorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continuation []byte `protobuf:"bytes,1,opt,name=continuation" json:"continuation,omitempty"`
	Exhausted    *bool  `protobuf:"varint,2,opt,name=exhausted" json:"exhausted,omitempty"`
	BloomFilter  []byte `protobuf:"bytes,3,opt,name=bloom_filter,json=bloomFilter" json:"bloom_filter,omitempty"`
}

func (x *ProbableIntersectionContinuation_CursorState) Reset() {
	*x = ProbableIntersectionContinuation_CursorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProbableIntersectionContinuation_CursorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbableIntersectionContinuation_CursorState) ProtoMessage() {}

func (x *ProbableIntersectionContinuation_CursorState) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbableIntersectionContinuation_CursorState.ProtoReflect.Descriptor instead.
func (*ProbableIntersectionContinuation_CursorState) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ProbableIntersectionContinuation_CursorState) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *ProbableIntersectionContinuation_CursorState) GetExhausted() bool {
	if x != nil && x.Exhausted != nil {
		return *x.Exhausted
	}
	return false
}

func (x *ProbableIntersectionContinuation_CursorState) GetBloomFilter() []byte {
	if x != nil {
		return x.BloomFilter
	}
	return nil
}

type ComposedBitmapIndexContinuation_CursorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continuation []byte `protobuf:"bytes,1,opt,name=continuation" json:"continuation,omitempty"`
	Exhausted    *bool  `protobuf:"varint,2,opt,name=exhausted" json:"exhausted,omitempty"`
}

func (x *ComposedBitmapIndexContinuation_CursorState) Reset() {
	*x = ComposedBitmapIndexContinuation_CursorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposedBitmapIndexContinuation_CursorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposedBitmapIndexContinuation_CursorState) ProtoMessage() {}

func (x *ComposedBitmapIndexContinuation_CursorState) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposedBitmapIndexContinuation_CursorState.ProtoReflect.Descriptor instead.
func (*ComposedBitmapIndexContinuation_CursorState) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ComposedBitmapIndexContinuation_CursorState) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *ComposedBitmapIndexContinuation_CursorState) GetExhausted() bool {
	if x != nil && x.Exhausted != nil {
		return *x.Exhausted
	}
	return false
}

type ComparatorContinuation_CursorState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Continuation []byte `protobuf:"bytes,1,opt,name=continuation" json:"continuation,omitempty"`
	Started      *bool  `protobuf:"varint,2,opt,name=started" json:"started,omitempty"`
}

func (x *ComparatorContinuation_CursorState) Reset() {
	*x = ComparatorContinuation_CursorState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_cursor_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComparatorContinuation_CursorState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparatorContinuation_CursorState) ProtoMessage() {}

func (x *ComparatorContinuation_CursorState) ProtoReflect() protoreflect.Message {
	mi := &file_record_cursor_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparatorContinuation_CursorState.ProtoReflect.Descriptor instead.
func (*ComparatorContinuation_CursorState) Descriptor() ([]byte, []int) {
	return file_record_cursor_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ComparatorContinuation_CursorState) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *ComparatorContinuation_CursorState) GetStarted() bool {
	if x != nil && x.Started != nil {
		return *x.Started
	}
	return false
}

var File_record_cursor_proto protoreflect.FileDescriptor

var file_record_cursor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65,
	0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x94, 0x01, 0x0a, 0x13, 0x46, 0x6c, 0x61, 0x74, 0x4d,
	0x61, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d,
	0x0a, 0x12, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a,
	0x12, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x69, 0x6e, 0x6e, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x84, 0x03,
	0x0a, 0x18, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x12, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x66, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x13, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x66, 0x69, 0x72, 0x73, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x6f, 0x0a, 0x11, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x43, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x43, 0x68, 0x69,
	0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x4b, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x22, 0x82, 0x03, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x12, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x66, 0x69, 0x72, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x13, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x5f, 0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x66, 0x69, 0x72, 0x73, 0x74, 0x45, 0x78, 0x68, 0x61, 0x75, 0x73,
	0x74, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x65, 0x78,
	0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x45, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x12, 0x68,
	0x0a, 0x11, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x43, 0x68,
	0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x4f, 0x0a, 0x0b, 0x43, 0x75, 0x72, 0x73,
	0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69,
	0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63,
	0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65,
	0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x22, 0x84, 0x02, 0x0a, 0x20, 0x50, 0x72,
	0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6c,
	0x0a, 0x0b, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x0a, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x72, 0x0a, 0x0b,
	0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x62, 0x6c, 0x6f, 0x6f, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x22, 0x50, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xa5, 0x01, 0x0a, 0x1a, 0x53, 0x69, 0x7a, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69,
	0x73, 0x74, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x63, 0x0a, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x53, 0x69,
	0x7a, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0xdc, 0x01, 0x0a, 0x1c, 0x53,
	0x69, 0x7a, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6b,
	0x65, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x78, 0x4b, 0x65, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x4b, 0x65, 0x79, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x0b, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65,
	0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x04, 0x42, 0x02, 0x10, 0x01, 0x52, 0x0b, 0x73, 0x69,
	0x7a, 0x65, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x12, 0x4f, 0x72,
	0x45, 0x6c, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x4d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x37, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x4f, 0x72, 0x45, 0x6c, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x0a, 0x09,
	0x55, 0x4e, 0x44, 0x45, 0x43, 0x49, 0x44, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55,
	0x53, 0x45, 0x5f, 0x49, 0x4e, 0x4e, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x53,
	0x45, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x02, 0x22, 0xdf, 0x01, 0x0a, 0x1f, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x42, 0x69, 0x74, 0x6d, 0x61, 0x70, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6b, 0x0a,
	0x0b, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x4a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x64, 0x42, 0x69, 0x74, 0x6d, 0x61,
	0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x4f, 0x0a, 0x0b, 0x43, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x65, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x22, 0x6e, 0x0a, 0x18, 0x53,
	0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x69,
	0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c,
	0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x2d, 0x0a, 0x12,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc9, 0x01, 0x0a, 0x16,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x62, 0x0a, 0x0b, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0a,
	0x63, 0x68, 0x69, 0x6c, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x4b, 0x0a, 0x0b, 0x43, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x6d, 0x0a, 0x25, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x53, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2a, 0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x69, 0x6c, 0x62, 0x65, 0x72, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74,
	0x48, 0x69, 0x6c, 0x62, 0x65, 0x72, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6c, 0x61, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6c,
	0x61, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x42, 0x27, 0x42, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x12, 0x63, 0x69, 0x6f,
	0x2f, 0x66, 0x64, 0x62, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x73, 0x72, 0x63,
}

var (
	file_record_cursor_proto_rawDescOnce sync.Once
	file_record_cursor_proto_rawDescData = file_record_cursor_proto_rawDesc
)

func file_record_cursor_proto_rawDescGZIP() []byte {
	file_record_cursor_proto_rawDescOnce.Do(func() {
		file_record_cursor_proto_rawDescData = protoimpl.X.CompressGZIP(file_record_cursor_proto_rawDescData)
	})
	return file_record_cursor_proto_rawDescData
}

var file_record_cursor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_record_cursor_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_record_cursor_proto_goTypes = []any{
	(OrElseContinuation_State)(0),                        // 0: com.apple.foundationdb.record.OrElseContinuation.State
	(*FlatMapContinuation)(nil),                          // 1: com.apple.foundationdb.record.FlatMapContinuation
	(*IntersectionContinuation)(nil),                     // 2: com.apple.foundationdb.record.IntersectionContinuation
	(*UnionContinuation)(nil),                            // 3: com.apple.foundationdb.record.UnionContinuation
	(*ProbableIntersectionContinuation)(nil),             // 4: com.apple.foundationdb.record.ProbableIntersectionContinuation
	(*ConcatContinuation)(nil),                           // 5: com.apple.foundationdb.record.ConcatContinuation
	(*SizeStatisticsContinuation)(nil),                   // 6: com.apple.foundationdb.record.SizeStatisticsContinuation
	(*SizeStatisticsPartialResults)(nil),                 // 7: com.apple.foundationdb.record.SizeStatisticsPartialResults
	(*OrElseContinuation)(nil),                           // 8: com.apple.foundationdb.record.OrElseContinuation
	(*ComposedBitmapIndexContinuation)(nil),              // 9: com.apple.foundationdb.record.ComposedBitmapIndexContinuation
	(*SelectorPlanContinuation)(nil),                     // 10: com.apple.foundationdb.record.SelectorPlanContinuation
	(*ComparatorContinuation)(nil),                       // 11: com.apple.foundationdb.record.ComparatorContinuation
	(*MultidimensionalIndexScanContinuation)(nil),        // 12: com.apple.foundationdb.record.MultidimensionalIndexScanContinuation
	(*IntersectionContinuation_CursorState)(nil),         // 13: com.apple.foundationdb.record.IntersectionContinuation.CursorState
	(*UnionContinuation_CursorState)(nil),                // 14: com.apple.foundationdb.record.UnionContinuation.CursorState
	(*ProbableIntersectionContinuation_CursorState)(nil), // 15: com.apple.foundationdb.record.ProbableIntersectionContinuation.CursorState
	(*ComposedBitmapIndexContinuation_CursorState)(nil),  // 16: com.apple.foundationdb.record.ComposedBitmapIndexContinuation.CursorState
	(*ComparatorContinuation_CursorState)(nil),           // 17: com.apple.foundationdb.record.ComparatorContinuation.CursorState
}
var file_record_cursor_proto_depIdxs = []int32{
	13, // 0: com.apple.foundationdb.record.IntersectionContinuation.other_child_state:type_name -> com.apple.foundationdb.record.IntersectionContinuation.CursorState
	14, // 1: com.apple.foundationdb.record.UnionContinuation.other_child_state:type_name -> com.apple.foundationdb.record.UnionContinuation.CursorState
	15, // 2: com.apple.foundationdb.record.ProbableIntersectionContinuation.child_state:type_name -> com.apple.foundationdb.record.ProbableIntersectionContinuation.CursorState
	7,  // 3: com.apple.foundationdb.record.SizeStatisticsContinuation.partialResults:type_name -> com.apple.foundationdb.record.SizeStatisticsPartialResults
	0,  // 4: com.apple.foundationdb.record.OrElseContinuation.state:type_name -> com.apple.foundationdb.record.OrElseContinuation.State
	16, // 5: com.apple.foundationdb.record.ComposedBitmapIndexContinuation.child_state:type_name -> com.apple.foundationdb.record.ComposedBitmapIndexContinuation.CursorState
	17, // 6: com.apple.foundationdb.record.ComparatorContinuation.child_state:type_name -> com.apple.foundationdb.record.ComparatorContinuation.CursorState
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_record_cursor_proto_init() }
func file_record_cursor_proto_init() {
	if File_record_cursor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_record_cursor_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FlatMapContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*IntersectionContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UnionContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ProbableIntersectionContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ConcatContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SizeStatisticsContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SizeStatisticsPartialResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*OrElseContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ComposedBitmapIndexContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SelectorPlanContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ComparatorContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*MultidimensionalIndexScanContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*IntersectionContinuation_CursorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*UnionContinuation_CursorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ProbableIntersectionContinuation_CursorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ComposedBitmapIndexContinuation_CursorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_cursor_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ComparatorContinuation_CursorState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_record_cursor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_cursor_proto_goTypes,
		DependencyIndexes: file_record_cursor_proto_depIdxs,
		EnumInfos:         file_record_cursor_proto_enumTypes,
		MessageInfos:      file_record_cursor_proto_msgTypes,
	}.Build()
	File_record_cursor_proto = out.File
	file_record_cursor_proto_rawDesc = nil
	file_record_cursor_proto_goTypes = nil
	file_record_cursor_proto_depIdxs = nil
}
