//
// record_sorting.proto
//
// This source file is part of the FoundationDB open source project
//
// Copyright 2021 Apple Inc. and the FoundationDB project authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: record_sorting.proto

package src

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortedRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrimaryKey []byte `protobuf:"bytes,1,opt,name=primary_key,json=primaryKey" json:"primary_key,omitempty"`
	Message    []byte `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Version    []byte `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (x *SortedRecord) Reset() {
	*x = SortedRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_sorting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortedRecord) ProtoMessage() {}

func (x *SortedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_record_sorting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortedRecord.ProtoReflect.Descriptor instead.
func (*SortedRecord) Descriptor() ([]byte, []int) {
	return file_record_sorting_proto_rawDescGZIP(), []int{0}
}

func (x *SortedRecord) GetPrimaryKey() []byte {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *SortedRecord) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SortedRecord) GetVersion() []byte {
	if x != nil {
		return x.Version
	}
	return nil
}

type MemorySortContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Records      [][]byte `protobuf:"bytes,1,rep,name=records" json:"records,omitempty"`
	MinimumKey   []byte   `protobuf:"bytes,2,opt,name=minimum_key,json=minimumKey" json:"minimum_key,omitempty"`
	Continuation []byte   `protobuf:"bytes,3,opt,name=continuation" json:"continuation,omitempty"`
}

func (x *MemorySortContinuation) Reset() {
	*x = MemorySortContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_sorting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemorySortContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySortContinuation) ProtoMessage() {}

func (x *MemorySortContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_sorting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySortContinuation.ProtoReflect.Descriptor instead.
func (*MemorySortContinuation) Descriptor() ([]byte, []int) {
	return file_record_sorting_proto_rawDescGZIP(), []int{1}
}

func (x *MemorySortContinuation) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *MemorySortContinuation) GetMinimumKey() []byte {
	if x != nil {
		return x.MinimumKey
	}
	return nil
}

func (x *MemorySortContinuation) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

type FileSortContinuation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Loading         *bool    `protobuf:"varint,1,opt,name=loading" json:"loading,omitempty"`
	InMemoryRecords [][]byte `protobuf:"bytes,2,rep,name=in_memory_records,json=inMemoryRecords" json:"in_memory_records,omitempty"`
	Files           []string `protobuf:"bytes,3,rep,name=files" json:"files,omitempty"`
	Continuation    []byte   `protobuf:"bytes,4,opt,name=continuation" json:"continuation,omitempty"`
	RecordPosition  *int32   `protobuf:"varint,5,opt,name=record_position,json=recordPosition" json:"record_position,omitempty"`
	FilePosition    *int64   `protobuf:"varint,6,opt,name=file_position,json=filePosition" json:"file_position,omitempty"`
}

func (x *FileSortContinuation) Reset() {
	*x = FileSortContinuation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_sorting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileSortContinuation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSortContinuation) ProtoMessage() {}

func (x *FileSortContinuation) ProtoReflect() protoreflect.Message {
	mi := &file_record_sorting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSortContinuation.ProtoReflect.Descriptor instead.
func (*FileSortContinuation) Descriptor() ([]byte, []int) {
	return file_record_sorting_proto_rawDescGZIP(), []int{2}
}

func (x *FileSortContinuation) GetLoading() bool {
	if x != nil && x.Loading != nil {
		return *x.Loading
	}
	return false
}

func (x *FileSortContinuation) GetInMemoryRecords() [][]byte {
	if x != nil {
		return x.InMemoryRecords
	}
	return nil
}

func (x *FileSortContinuation) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *FileSortContinuation) GetContinuation() []byte {
	if x != nil {
		return x.Continuation
	}
	return nil
}

func (x *FileSortContinuation) GetRecordPosition() int32 {
	if x != nil && x.RecordPosition != nil {
		return *x.RecordPosition
	}
	return 0
}

func (x *FileSortContinuation) GetFilePosition() int64 {
	if x != nil && x.FilePosition != nil {
		return *x.FilePosition
	}
	return 0
}

type SortFileHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version          *int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	MetaDataVersion  *int32  `protobuf:"varint,2,opt,name=meta_data_version,json=metaDataVersion" json:"meta_data_version,omitempty"`
	NumberOfSections *uint32 `protobuf:"fixed32,3,opt,name=number_of_sections,json=numberOfSections" json:"number_of_sections,omitempty"`
	NumberOfRecords  *uint32 `protobuf:"fixed32,4,opt,name=number_of_records,json=numberOfRecords" json:"number_of_records,omitempty"`
}

func (x *SortFileHeader) Reset() {
	*x = SortFileHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_sorting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortFileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortFileHeader) ProtoMessage() {}

func (x *SortFileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_record_sorting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortFileHeader.ProtoReflect.Descriptor instead.
func (*SortFileHeader) Descriptor() ([]byte, []int) {
	return file_record_sorting_proto_rawDescGZIP(), []int{3}
}

func (x *SortFileHeader) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SortFileHeader) GetMetaDataVersion() int32 {
	if x != nil && x.MetaDataVersion != nil {
		return *x.MetaDataVersion
	}
	return 0
}

func (x *SortFileHeader) GetNumberOfSections() uint32 {
	if x != nil && x.NumberOfSections != nil {
		return *x.NumberOfSections
	}
	return 0
}

func (x *SortFileHeader) GetNumberOfRecords() uint32 {
	if x != nil && x.NumberOfRecords != nil {
		return *x.NumberOfRecords
	}
	return 0
}

type SortSectionHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SectionNumber     *uint32 `protobuf:"fixed32,1,opt,name=section_number,json=sectionNumber" json:"section_number,omitempty"`
	StartRecordNumber *uint32 `protobuf:"fixed32,2,opt,name=start_record_number,json=startRecordNumber" json:"start_record_number,omitempty"`
	NumberOfRecords   *uint32 `protobuf:"fixed32,3,opt,name=number_of_records,json=numberOfRecords" json:"number_of_records,omitempty"`
	NumberOfBytes     *uint64 `protobuf:"fixed64,4,opt,name=number_of_bytes,json=numberOfBytes" json:"number_of_bytes,omitempty"`
	EncryptionIv      []byte  `protobuf:"bytes,5,opt,name=encryption_iv,json=encryptionIv" json:"encryption_iv,omitempty"`
}

func (x *SortSectionHeader) Reset() {
	*x = SortSectionHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_record_sorting_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortSectionHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortSectionHeader) ProtoMessage() {}

func (x *SortSectionHeader) ProtoReflect() protoreflect.Message {
	mi := &file_record_sorting_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortSectionHeader.ProtoReflect.Descriptor instead.
func (*SortSectionHeader) Descriptor() ([]byte, []int) {
	return file_record_sorting_proto_rawDescGZIP(), []int{4}
}

func (x *SortSectionHeader) GetSectionNumber() uint32 {
	if x != nil && x.SectionNumber != nil {
		return *x.SectionNumber
	}
	return 0
}

func (x *SortSectionHeader) GetStartRecordNumber() uint32 {
	if x != nil && x.StartRecordNumber != nil {
		return *x.StartRecordNumber
	}
	return 0
}

func (x *SortSectionHeader) GetNumberOfRecords() uint32 {
	if x != nil && x.NumberOfRecords != nil {
		return *x.NumberOfRecords
	}
	return 0
}

func (x *SortSectionHeader) GetNumberOfBytes() uint64 {
	if x != nil && x.NumberOfBytes != nil {
		return *x.NumberOfBytes
	}
	return 0
}

func (x *SortSectionHeader) GetEncryptionIv() []byte {
	if x != nil {
		return x.EncryptionIv
	}
	return nil
}

var File_record_sorting_proto protoreflect.FileDescriptor

var file_record_sorting_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c,
	0x65, 0x2e, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x63, 0x0a, 0x0c, 0x53, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x79, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x77, 0x0a, 0x16,
	0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x4b, 0x65,
	0x79, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xe4, 0x01, 0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x6f,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x6c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6c, 0x6f, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x6e, 0x5f, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x0f, 0x69, 0x6e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb0, 0x01, 0x0a,
	0x0e, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x74,
	0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f,
	0x6f, 0x66, 0x5f, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x07, 0x52, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x53, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66,
	0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x22,
	0xe3, 0x01, 0x0a, 0x11, 0x53, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0d, 0x73,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x13,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x11, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x11,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x06, 0x52, 0x0d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69,
	0x76, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x76, 0x42, 0x28, 0x42, 0x12, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x53,
	0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x12, 0x63, 0x69, 0x6f,
	0x2f, 0x66, 0x64, 0x62, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x73, 0x72, 0x63,
}

var (
	file_record_sorting_proto_rawDescOnce sync.Once
	file_record_sorting_proto_rawDescData = file_record_sorting_proto_rawDesc
)

func file_record_sorting_proto_rawDescGZIP() []byte {
	file_record_sorting_proto_rawDescOnce.Do(func() {
		file_record_sorting_proto_rawDescData = protoimpl.X.CompressGZIP(file_record_sorting_proto_rawDescData)
	})
	return file_record_sorting_proto_rawDescData
}

var file_record_sorting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_record_sorting_proto_goTypes = []any{
	(*SortedRecord)(nil),           // 0: com.apple.foundationdb.record.SortedRecord
	(*MemorySortContinuation)(nil), // 1: com.apple.foundationdb.record.MemorySortContinuation
	(*FileSortContinuation)(nil),   // 2: com.apple.foundationdb.record.FileSortContinuation
	(*SortFileHeader)(nil),         // 3: com.apple.foundationdb.record.SortFileHeader
	(*SortSectionHeader)(nil),      // 4: com.apple.foundationdb.record.SortSectionHeader
}
var file_record_sorting_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_record_sorting_proto_init() }
func file_record_sorting_proto_init() {
	if File_record_sorting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_record_sorting_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SortedRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_sorting_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MemorySortContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_sorting_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FileSortContinuation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_sorting_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SortFileHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_record_sorting_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SortSectionHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_record_sorting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_sorting_proto_goTypes,
		DependencyIndexes: file_record_sorting_proto_depIdxs,
		MessageInfos:      file_record_sorting_proto_msgTypes,
	}.Build()
	File_record_sorting_proto = out.File
	file_record_sorting_proto_rawDesc = nil
	file_record_sorting_proto_goTypes = nil
	file_record_sorting_proto_depIdxs = nil
}
