//
// tuple_fields.proto
//
// This source file is part of the FoundationDB open source project
//
// Copyright 2015-2018 Apple Inc. and the FoundationDB project authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: tuple_fields.proto

package src

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 2 64-bit fields is two tags, the same as 1 bytes field with a length of 16 would be.
	// fixed64 would be closer to how these are really used, but would fail the unsigned validator.
	MostSignificantBits  *int64 `protobuf:"fixed64,1,opt,name=most_significant_bits,json=mostSignificantBits" json:"most_significant_bits,omitempty"`
	LeastSignificantBits *int64 `protobuf:"fixed64,2,opt,name=least_significant_bits,json=leastSignificantBits" json:"least_significant_bits,omitempty"`
}

func (x *UUID) Reset() {
	*x = UUID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetMostSignificantBits() int64 {
	if x != nil && x.MostSignificantBits != nil {
		return *x.MostSignificantBits
	}
	return 0
}

func (x *UUID) GetLeastSignificantBits() int64 {
	if x != nil && x.LeastSignificantBits != nil {
		return *x.LeastSignificantBits
	}
	return 0
}

type NullableDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
}

func (x *NullableDouble) Reset() {
	*x = NullableDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableDouble) ProtoMessage() {}

func (x *NullableDouble) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableDouble.ProtoReflect.Descriptor instead.
func (*NullableDouble) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{1}
}

func (x *NullableDouble) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type NullableFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *float32 `protobuf:"fixed32,1,opt,name=value" json:"value,omitempty"`
}

func (x *NullableFloat) Reset() {
	*x = NullableFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableFloat) ProtoMessage() {}

func (x *NullableFloat) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableFloat.ProtoReflect.Descriptor instead.
func (*NullableFloat) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{2}
}

func (x *NullableFloat) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type NullableInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (x *NullableInt32) Reset() {
	*x = NullableInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableInt32) ProtoMessage() {}

func (x *NullableInt32) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableInt32.ProtoReflect.Descriptor instead.
func (*NullableInt32) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{3}
}

func (x *NullableInt32) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type NullableInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *int64 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (x *NullableInt64) Reset() {
	*x = NullableInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableInt64) ProtoMessage() {}

func (x *NullableInt64) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableInt64.ProtoReflect.Descriptor instead.
func (*NullableInt64) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{4}
}

func (x *NullableInt64) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type NullableBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (x *NullableBool) Reset() {
	*x = NullableBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableBool) ProtoMessage() {}

func (x *NullableBool) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableBool.ProtoReflect.Descriptor instead.
func (*NullableBool) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{5}
}

func (x *NullableBool) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

type NullableString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (x *NullableString) Reset() {
	*x = NullableString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableString) ProtoMessage() {}

func (x *NullableString) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableString.ProtoReflect.Descriptor instead.
func (*NullableString) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{6}
}

func (x *NullableString) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type NullableBytes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (x *NullableBytes) Reset() {
	*x = NullableBytes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tuple_fields_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullableBytes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullableBytes) ProtoMessage() {}

func (x *NullableBytes) ProtoReflect() protoreflect.Message {
	mi := &file_tuple_fields_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullableBytes.ProtoReflect.Descriptor instead.
func (*NullableBytes) Descriptor() ([]byte, []int) {
	return file_tuple_fields_proto_rawDescGZIP(), []int{7}
}

func (x *NullableBytes) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_tuple_fields_proto protoreflect.FileDescriptor

var file_tuple_fields_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x70, 0x70, 0x6c, 0x65, 0x2e,
	0x66, 0x6f, 0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x22, 0x70, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x15, 0x6d,
	0x6f, 0x73, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x5f,
	0x62, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x10, 0x52, 0x13, 0x6d, 0x6f, 0x73, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x42, 0x69, 0x74, 0x73, 0x12,
	0x34, 0x0a, 0x16, 0x6c, 0x65, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x6e, 0x74, 0x5f, 0x62, 0x69, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x10, 0x52,
	0x14, 0x6c, 0x65, 0x61, 0x73, 0x74, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x66, 0x69, 0x63, 0x61, 0x6e,
	0x74, 0x42, 0x69, 0x74, 0x73, 0x22, 0x26, 0x0a, 0x0e, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a,
	0x0d, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x25, 0x0a, 0x0d, 0x4e,
	0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x24, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x6f,
	0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x4e, 0x75, 0x6c, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x25, 0x0a, 0x0d, 0x4e, 0x75, 0x6c, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x26, 0x42, 0x10, 0x54, 0x75, 0x70, 0x6c, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x12, 0x63, 0x69, 0x6f,
	0x2f, 0x66, 0x64, 0x62, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2f, 0x73, 0x72, 0x63,
}

var (
	file_tuple_fields_proto_rawDescOnce sync.Once
	file_tuple_fields_proto_rawDescData = file_tuple_fields_proto_rawDesc
)

func file_tuple_fields_proto_rawDescGZIP() []byte {
	file_tuple_fields_proto_rawDescOnce.Do(func() {
		file_tuple_fields_proto_rawDescData = protoimpl.X.CompressGZIP(file_tuple_fields_proto_rawDescData)
	})
	return file_tuple_fields_proto_rawDescData
}

var file_tuple_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_tuple_fields_proto_goTypes = []any{
	(*UUID)(nil),           // 0: com.apple.foundationdb.record.UUID
	(*NullableDouble)(nil), // 1: com.apple.foundationdb.record.NullableDouble
	(*NullableFloat)(nil),  // 2: com.apple.foundationdb.record.NullableFloat
	(*NullableInt32)(nil),  // 3: com.apple.foundationdb.record.NullableInt32
	(*NullableInt64)(nil),  // 4: com.apple.foundationdb.record.NullableInt64
	(*NullableBool)(nil),   // 5: com.apple.foundationdb.record.NullableBool
	(*NullableString)(nil), // 6: com.apple.foundationdb.record.NullableString
	(*NullableBytes)(nil),  // 7: com.apple.foundationdb.record.NullableBytes
}
var file_tuple_fields_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tuple_fields_proto_init() }
func file_tuple_fields_proto_init() {
	if File_tuple_fields_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tuple_fields_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UUID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_fields_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*NullableDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_fields_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*NullableFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_fields_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*NullableInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_fields_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*NullableInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_fields_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*NullableBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_fields_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*NullableString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tuple_fields_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*NullableBytes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tuple_fields_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tuple_fields_proto_goTypes,
		DependencyIndexes: file_tuple_fields_proto_depIdxs,
		MessageInfos:      file_tuple_fields_proto_msgTypes,
	}.Build()
	File_tuple_fields_proto = out.File
	file_tuple_fields_proto_rawDesc = nil
	file_tuple_fields_proto_goTypes = nil
	file_tuple_fields_proto_depIdxs = nil
}
