// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: filters.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reducer_REDUCTION int32

const (
	Reducer_AND Reducer_REDUCTION = 0
	Reducer_OR  Reducer_REDUCTION = 1
)

// Enum value maps for Reducer_REDUCTION.
var (
	Reducer_REDUCTION_name = map[int32]string{
		0: "AND",
		1: "OR",
	}
	Reducer_REDUCTION_value = map[string]int32{
		"AND": 0,
		"OR":  1,
	}
)

func (x Reducer_REDUCTION) Enum() *Reducer_REDUCTION {
	p := new(Reducer_REDUCTION)
	*p = x
	return p
}

func (x Reducer_REDUCTION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reducer_REDUCTION) Descriptor() protoreflect.EnumDescriptor {
	return file_filters_proto_enumTypes[0].Descriptor()
}

func (Reducer_REDUCTION) Type() protoreflect.EnumType {
	return &file_filters_proto_enumTypes[0]
}

func (x Reducer_REDUCTION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reducer_REDUCTION.Descriptor instead.
func (Reducer_REDUCTION) EnumDescriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{0, 0}
}

type Operator_OPERATION int32

const (
	Operator_EQ   Operator_OPERATION = 0
	Operator_N_EQ Operator_OPERATION = 1
	Operator_GT   Operator_OPERATION = 2
	Operator_GTE  Operator_OPERATION = 3
	Operator_LT   Operator_OPERATION = 4
	Operator_LTE  Operator_OPERATION = 5
	Operator_IN   Operator_OPERATION = 6
)

// Enum value maps for Operator_OPERATION.
var (
	Operator_OPERATION_name = map[int32]string{
		0: "EQ",
		1: "N_EQ",
		2: "GT",
		3: "GTE",
		4: "LT",
		5: "LTE",
		6: "IN",
	}
	Operator_OPERATION_value = map[string]int32{
		"EQ":   0,
		"N_EQ": 1,
		"GT":   2,
		"GTE":  3,
		"LT":   4,
		"LTE":  5,
		"IN":   6,
	}
)

func (x Operator_OPERATION) Enum() *Operator_OPERATION {
	p := new(Operator_OPERATION)
	*p = x
	return p
}

func (x Operator_OPERATION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operator_OPERATION) Descriptor() protoreflect.EnumDescriptor {
	return file_filters_proto_enumTypes[1].Descriptor()
}

func (Operator_OPERATION) Type() protoreflect.EnumType {
	return &file_filters_proto_enumTypes[1]
}

func (x Operator_OPERATION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operator_OPERATION.Descriptor instead.
func (Operator_OPERATION) EnumDescriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{1, 0}
}

type Reducer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rduction Reducer_REDUCTION `protobuf:"varint,10,opt,name=rduction,proto3,enum=cio.fdb.record.grpc.Reducer_REDUCTION" json:"rduction,omitempty"`
}

func (x *Reducer) Reset() {
	*x = Reducer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reducer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reducer) ProtoMessage() {}

func (x *Reducer) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reducer.ProtoReflect.Descriptor instead.
func (*Reducer) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{0}
}

func (x *Reducer) GetRduction() Reducer_REDUCTION {
	if x != nil {
		return x.Rduction
	}
	return Reducer_AND
}

type Operator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation Operator_OPERATION `protobuf:"varint,20,opt,name=operation,proto3,enum=cio.fdb.record.grpc.Operator_OPERATION" json:"operation,omitempty"`
}

func (x *Operator) Reset() {
	*x = Operator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{1}
}

func (x *Operator) GetOperation() Operator_OPERATION {
	if x != nil {
		return x.Operation
	}
	return Operator_EQ
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nested []*Field `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetNested() []*Field {
	if x != nil {
		return x.Nested
	}
	return nil
}

type IntList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []int32 `protobuf:"varint,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *IntList) Reset() {
	*x = IntList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntList) ProtoMessage() {}

func (x *IntList) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntList.ProtoReflect.Descriptor instead.
func (*IntList) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{3}
}

func (x *IntList) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

type DoubleList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []float64 `protobuf:"fixed64,1,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *DoubleList) Reset() {
	*x = DoubleList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleList) ProtoMessage() {}

func (x *DoubleList) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleList.ProtoReflect.Descriptor instead.
func (*DoubleList) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{4}
}

func (x *DoubleList) GetValue() []float64 {
	if x != nil {
		return x.Value
	}
	return nil
}

type StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
}

func (x *StringList) Reset() {
	*x = StringList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{5}
}

func (x *StringList) GetValue() []string {
	if x != nil {
		return x.Value
	}
	return nil
}

type Operand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Expression:
	//
	//	*Operand_IntValue
	//	*Operand_DoubleValue
	//	*Operand_StringValue
	//	*Operand_IntListValue
	//	*Operand_DoubleListValue
	//	*Operand_StringListValue
	Expression isOperand_Expression `protobuf_oneof:"expression"`
}

func (x *Operand) Reset() {
	*x = Operand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operand) ProtoMessage() {}

func (x *Operand) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operand.ProtoReflect.Descriptor instead.
func (*Operand) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{6}
}

func (m *Operand) GetExpression() isOperand_Expression {
	if m != nil {
		return m.Expression
	}
	return nil
}

func (x *Operand) GetIntValue() int32 {
	if x, ok := x.GetExpression().(*Operand_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *Operand) GetDoubleValue() float64 {
	if x, ok := x.GetExpression().(*Operand_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *Operand) GetStringValue() string {
	if x, ok := x.GetExpression().(*Operand_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *Operand) GetIntListValue() *IntList {
	if x, ok := x.GetExpression().(*Operand_IntListValue); ok {
		return x.IntListValue
	}
	return nil
}

func (x *Operand) GetDoubleListValue() *DoubleList {
	if x, ok := x.GetExpression().(*Operand_DoubleListValue); ok {
		return x.DoubleListValue
	}
	return nil
}

func (x *Operand) GetStringListValue() *StringList {
	if x, ok := x.GetExpression().(*Operand_StringListValue); ok {
		return x.StringListValue
	}
	return nil
}

type isOperand_Expression interface {
	isOperand_Expression()
}

type Operand_IntValue struct {
	IntValue int32 `protobuf:"varint,8,opt,name=intValue,proto3,oneof"`
}

type Operand_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,12,opt,name=doubleValue,proto3,oneof"`
}

type Operand_StringValue struct {
	StringValue string `protobuf:"bytes,16,opt,name=stringValue,proto3,oneof"`
}

type Operand_IntListValue struct {
	IntListValue *IntList `protobuf:"bytes,20,opt,name=intListValue,proto3,oneof"`
}

type Operand_DoubleListValue struct {
	DoubleListValue *DoubleList `protobuf:"bytes,24,opt,name=doubleListValue,proto3,oneof"`
}

type Operand_StringListValue struct {
	StringListValue *StringList `protobuf:"bytes,28,opt,name=stringListValue,proto3,oneof"`
}

func (*Operand_IntValue) isOperand_Expression() {}

func (*Operand_DoubleValue) isOperand_Expression() {}

func (*Operand_StringValue) isOperand_Expression() {}

func (*Operand_IntListValue) isOperand_Expression() {}

func (*Operand_DoubleListValue) isOperand_Expression() {}

func (*Operand_StringListValue) isOperand_Expression() {}

type BooleanExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator *Operator `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Field    *Field    `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value    *Operand  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BooleanExpression) Reset() {
	*x = BooleanExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooleanExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanExpression) ProtoMessage() {}

func (x *BooleanExpression) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanExpression.ProtoReflect.Descriptor instead.
func (*BooleanExpression) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{7}
}

func (x *BooleanExpression) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *BooleanExpression) GetField() *Field {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *BooleanExpression) GetValue() *Operand {
	if x != nil {
		return x.Value
	}
	return nil
}

type BooleanQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reducer     *Reducer             `protobuf:"bytes,1,opt,name=reducer,proto3" json:"reducer,omitempty"`
	Expressions []*BooleanExpression `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
}

func (x *BooleanQuery) Reset() {
	*x = BooleanQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filters_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooleanQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanQuery) ProtoMessage() {}

func (x *BooleanQuery) ProtoReflect() protoreflect.Message {
	mi := &file_filters_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanQuery.ProtoReflect.Descriptor instead.
func (*BooleanQuery) Descriptor() ([]byte, []int) {
	return file_filters_proto_rawDescGZIP(), []int{8}
}

func (x *BooleanQuery) GetReducer() *Reducer {
	if x != nil {
		return x.Reducer
	}
	return nil
}

func (x *BooleanQuery) GetExpressions() []*BooleanExpression {
	if x != nil {
		return x.Expressions
	}
	return nil
}

var File_filters_proto protoreflect.FileDescriptor

var file_filters_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x22, 0x6b, 0x0a, 0x07, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12,
	0x42, 0x0a, 0x08, 0x72, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x26, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x2e,
	0x52, 0x45, 0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x08, 0x72, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x1c, 0x0a, 0x09, 0x52, 0x45, 0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x52, 0x10,
	0x01, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x45,
	0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x27, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x09, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x12, 0x06, 0x0a, 0x02, 0x45, 0x51, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x5f,
	0x45, 0x51, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03,
	0x47, 0x54, 0x45, 0x10, 0x03, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x54, 0x10, 0x04, 0x12, 0x07, 0x0a,
	0x03, 0x4c, 0x54, 0x45, 0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x4e, 0x10, 0x06, 0x22, 0x4f,
	0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x69,
	0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22,
	0x1f, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x22, 0x0a, 0x0a, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xdb, 0x02, 0x0a, 0x07, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x69, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x49, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0c, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4b,
	0x0a, 0x0f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64,
	0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x64, 0x6f, 0x75, 0x62,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x1c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xb4, 0x01, 0x0a, 0x11, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x08,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x30, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62,
	0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66,
	0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x90, 0x01,
	0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x36,
	0x0a, 0x07, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x07, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x69,
	0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x2a, 0x0a, 0x13, 0x63, 0x69, 0x6f, 0x2e, 0x66, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5a, 0x13, 0x63, 0x69, 0x6f, 0x2f, 0x66, 0x64, 0x62,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filters_proto_rawDescOnce sync.Once
	file_filters_proto_rawDescData = file_filters_proto_rawDesc
)

func file_filters_proto_rawDescGZIP() []byte {
	file_filters_proto_rawDescOnce.Do(func() {
		file_filters_proto_rawDescData = protoimpl.X.CompressGZIP(file_filters_proto_rawDescData)
	})
	return file_filters_proto_rawDescData
}

var file_filters_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_filters_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_filters_proto_goTypes = []any{
	(Reducer_REDUCTION)(0),    // 0: cio.fdb.record.grpc.Reducer.REDUCTION
	(Operator_OPERATION)(0),   // 1: cio.fdb.record.grpc.Operator.OPERATION
	(*Reducer)(nil),           // 2: cio.fdb.record.grpc.Reducer
	(*Operator)(nil),          // 3: cio.fdb.record.grpc.Operator
	(*Field)(nil),             // 4: cio.fdb.record.grpc.Field
	(*IntList)(nil),           // 5: cio.fdb.record.grpc.IntList
	(*DoubleList)(nil),        // 6: cio.fdb.record.grpc.DoubleList
	(*StringList)(nil),        // 7: cio.fdb.record.grpc.StringList
	(*Operand)(nil),           // 8: cio.fdb.record.grpc.Operand
	(*BooleanExpression)(nil), // 9: cio.fdb.record.grpc.BooleanExpression
	(*BooleanQuery)(nil),      // 10: cio.fdb.record.grpc.BooleanQuery
}
var file_filters_proto_depIdxs = []int32{
	0,  // 0: cio.fdb.record.grpc.Reducer.rduction:type_name -> cio.fdb.record.grpc.Reducer.REDUCTION
	1,  // 1: cio.fdb.record.grpc.Operator.operation:type_name -> cio.fdb.record.grpc.Operator.OPERATION
	4,  // 2: cio.fdb.record.grpc.Field.nested:type_name -> cio.fdb.record.grpc.Field
	5,  // 3: cio.fdb.record.grpc.Operand.intListValue:type_name -> cio.fdb.record.grpc.IntList
	6,  // 4: cio.fdb.record.grpc.Operand.doubleListValue:type_name -> cio.fdb.record.grpc.DoubleList
	7,  // 5: cio.fdb.record.grpc.Operand.stringListValue:type_name -> cio.fdb.record.grpc.StringList
	3,  // 6: cio.fdb.record.grpc.BooleanExpression.operator:type_name -> cio.fdb.record.grpc.Operator
	4,  // 7: cio.fdb.record.grpc.BooleanExpression.field:type_name -> cio.fdb.record.grpc.Field
	8,  // 8: cio.fdb.record.grpc.BooleanExpression.value:type_name -> cio.fdb.record.grpc.Operand
	2,  // 9: cio.fdb.record.grpc.BooleanQuery.reducer:type_name -> cio.fdb.record.grpc.Reducer
	9,  // 10: cio.fdb.record.grpc.BooleanQuery.expressions:type_name -> cio.fdb.record.grpc.BooleanExpression
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_filters_proto_init() }
func file_filters_proto_init() {
	if File_filters_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filters_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Reducer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Operator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IntList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DoubleList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*StringList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Operand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BooleanExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filters_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*BooleanQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_filters_proto_msgTypes[6].OneofWrappers = []any{
		(*Operand_IntValue)(nil),
		(*Operand_DoubleValue)(nil),
		(*Operand_StringValue)(nil),
		(*Operand_IntListValue)(nil),
		(*Operand_DoubleListValue)(nil),
		(*Operand_StringListValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filters_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filters_proto_goTypes,
		DependencyIndexes: file_filters_proto_depIdxs,
		EnumInfos:         file_filters_proto_enumTypes,
		MessageInfos:      file_filters_proto_msgTypes,
	}.Build()
	File_filters_proto = out.File
	file_filters_proto_rawDesc = nil
	file_filters_proto_goTypes = nil
	file_filters_proto_depIdxs = nil
}
